### ISSUE TITLE
Custom Element are not compatible with firefox

### ISSUE THREAD

**Issue by wesguirra** [jcgregorio/stamp#2]
**ns.newElement function** call **window.customElements** but this function **isn't available when using firefox or internet explorer**, that what MDN says:

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements#Browser_compatibility

why not use existing html elements for better crossbrowser compatibility?

**Comment by jcgregorio** [comment]
I have removed the code for <host-content> as the Shadow DOM spec is stabilizing on <slot>. I've also added an example Custom Element that uses Shadow DOM, <slot>, and Stamp for templating.

While the Custom Elements example will require a polyfill to run on all browsers, Stamp itself should run on all browsers w/o a polyfill as long as they support the <template> tag.

I've cut a v2.0.0 release with these changes.
